// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.5
// source: proto/game.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Снимок мира (сервер -> клиент)
type WorldSnapshot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tick          uint64                 `protobuf:"varint,1,opt,name=tick,proto3" json:"tick,omitempty"`
	Snakes        []*Snake               `protobuf:"bytes,2,rep,name=snakes,proto3" json:"snakes,omitempty"`
	Coins         []*Coin                `protobuf:"bytes,3,rep,name=coins,proto3" json:"coins,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorldSnapshot) Reset() {
	*x = WorldSnapshot{}
	mi := &file_proto_game_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorldSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorldSnapshot) ProtoMessage() {}

func (x *WorldSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_proto_game_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorldSnapshot.ProtoReflect.Descriptor instead.
func (*WorldSnapshot) Descriptor() ([]byte, []int) {
	return file_proto_game_proto_rawDescGZIP(), []int{0}
}

func (x *WorldSnapshot) GetTick() uint64 {
	if x != nil {
		return x.Tick
	}
	return 0
}

func (x *WorldSnapshot) GetSnakes() []*Snake {
	if x != nil {
		return x.Snakes
	}
	return nil
}

func (x *WorldSnapshot) GetCoins() []*Coin {
	if x != nil {
		return x.Coins
	}
	return nil
}

type Snake struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Head          *Point                 `protobuf:"bytes,2,opt,name=head,proto3" json:"head,omitempty"`
	Body          []*Point               `protobuf:"bytes,3,rep,name=body,proto3" json:"body,omitempty"`
	Angle         float32                `protobuf:"fixed32,4,opt,name=angle,proto3" json:"angle,omitempty"`
	Score         float32                `protobuf:"fixed32,5,opt,name=score,proto3" json:"score,omitempty"`
	BodyLength    int32                  `protobuf:"varint,6,opt,name=body_length,json=bodyLength,proto3" json:"body_length,omitempty"` // кол-во сегментов (head + tail). Нужно при body=[] для своей змеи
	SkinId        int32                  `protobuf:"varint,7,opt,name=skin_id,json=skinId,proto3" json:"skin_id,omitempty"`             // индекс цвета/скина (0-8 для палитры Slither)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Snake) Reset() {
	*x = Snake{}
	mi := &file_proto_game_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Snake) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Snake) ProtoMessage() {}

func (x *Snake) ProtoReflect() protoreflect.Message {
	mi := &file_proto_game_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Snake.ProtoReflect.Descriptor instead.
func (*Snake) Descriptor() ([]byte, []int) {
	return file_proto_game_proto_rawDescGZIP(), []int{1}
}

func (x *Snake) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Snake) GetHead() *Point {
	if x != nil {
		return x.Head
	}
	return nil
}

func (x *Snake) GetBody() []*Point {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *Snake) GetAngle() float32 {
	if x != nil {
		return x.Angle
	}
	return 0
}

func (x *Snake) GetScore() float32 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *Snake) GetBodyLength() int32 {
	if x != nil {
		return x.BodyLength
	}
	return 0
}

func (x *Snake) GetSkinId() int32 {
	if x != nil {
		return x.SkinId
	}
	return 0
}

type Coin struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Pos           *Point                 `protobuf:"bytes,2,opt,name=pos,proto3" json:"pos,omitempty"`
	Value         float32                `protobuf:"fixed32,3,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Coin) Reset() {
	*x = Coin{}
	mi := &file_proto_game_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Coin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Coin) ProtoMessage() {}

func (x *Coin) ProtoReflect() protoreflect.Message {
	mi := &file_proto_game_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Coin.ProtoReflect.Descriptor instead.
func (*Coin) Descriptor() ([]byte, []int) {
	return file_proto_game_proto_rawDescGZIP(), []int{2}
}

func (x *Coin) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Coin) GetPos() *Point {
	if x != nil {
		return x.Pos
	}
	return nil
}

func (x *Coin) GetValue() float32 {
	if x != nil {
		return x.Value
	}
	return 0
}

type Point struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X             float32                `protobuf:"fixed32,1,opt,name=x,proto3" json:"x,omitempty"`
	Y             float32                `protobuf:"fixed32,2,opt,name=y,proto3" json:"y,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Point) Reset() {
	*x = Point{}
	mi := &file_proto_game_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Point) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Point) ProtoMessage() {}

func (x *Point) ProtoReflect() protoreflect.Message {
	mi := &file_proto_game_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Point.ProtoReflect.Descriptor instead.
func (*Point) Descriptor() ([]byte, []int) {
	return file_proto_game_proto_rawDescGZIP(), []int{3}
}

func (x *Point) GetX() float32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Point) GetY() float32 {
	if x != nil {
		return x.Y
	}
	return 0
}

// Ввод игрока (клиент -> сервер)
type PlayerInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Angle         float32                `protobuf:"fixed32,1,opt,name=angle,proto3" json:"angle,omitempty"`
	Boost         bool                   `protobuf:"varint,2,opt,name=boost,proto3" json:"boost,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerInput) Reset() {
	*x = PlayerInput{}
	mi := &file_proto_game_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerInput) ProtoMessage() {}

func (x *PlayerInput) ProtoReflect() protoreflect.Message {
	mi := &file_proto_game_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerInput.ProtoReflect.Descriptor instead.
func (*PlayerInput) Descriptor() ([]byte, []int) {
	return file_proto_game_proto_rawDescGZIP(), []int{4}
}

func (x *PlayerInput) GetAngle() float32 {
	if x != nil {
		return x.Angle
	}
	return 0
}

func (x *PlayerInput) GetBoost() bool {
	if x != nil {
		return x.Boost
	}
	return false
}

var File_proto_game_proto protoreflect.FileDescriptor

const file_proto_game_proto_rawDesc = "" +
	"\n" +
	"\x10proto/game.proto\x12\x04game\"j\n" +
	"\rWorldSnapshot\x12\x12\n" +
	"\x04tick\x18\x01 \x01(\x04R\x04tick\x12#\n" +
	"\x06snakes\x18\x02 \x03(\v2\v.game.SnakeR\x06snakes\x12 \n" +
	"\x05coins\x18\x03 \x03(\v2\n" +
	".game.CoinR\x05coins\"\xbf\x01\n" +
	"\x05Snake\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x1f\n" +
	"\x04head\x18\x02 \x01(\v2\v.game.PointR\x04head\x12\x1f\n" +
	"\x04body\x18\x03 \x03(\v2\v.game.PointR\x04body\x12\x14\n" +
	"\x05angle\x18\x04 \x01(\x02R\x05angle\x12\x14\n" +
	"\x05score\x18\x05 \x01(\x02R\x05score\x12\x1f\n" +
	"\vbody_length\x18\x06 \x01(\x05R\n" +
	"bodyLength\x12\x17\n" +
	"\askin_id\x18\a \x01(\x05R\x06skinId\"K\n" +
	"\x04Coin\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\x03pos\x18\x02 \x01(\v2\v.game.PointR\x03pos\x12\x14\n" +
	"\x05value\x18\x03 \x01(\x02R\x05value\"#\n" +
	"\x05Point\x12\f\n" +
	"\x01x\x18\x01 \x01(\x02R\x01x\x12\f\n" +
	"\x01y\x18\x02 \x01(\x02R\x01y\"9\n" +
	"\vPlayerInput\x12\x14\n" +
	"\x05angle\x18\x01 \x01(\x02R\x05angle\x12\x14\n" +
	"\x05boost\x18\x02 \x01(\bR\x05boostB,Z*github.com/crypto-snake-arena/server/protob\x06proto3"

var (
	file_proto_game_proto_rawDescOnce sync.Once
	file_proto_game_proto_rawDescData []byte
)

func file_proto_game_proto_rawDescGZIP() []byte {
	file_proto_game_proto_rawDescOnce.Do(func() {
		file_proto_game_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_game_proto_rawDesc), len(file_proto_game_proto_rawDesc)))
	})
	return file_proto_game_proto_rawDescData
}

var file_proto_game_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_game_proto_goTypes = []any{
	(*WorldSnapshot)(nil), // 0: game.WorldSnapshot
	(*Snake)(nil),         // 1: game.Snake
	(*Coin)(nil),          // 2: game.Coin
	(*Point)(nil),         // 3: game.Point
	(*PlayerInput)(nil),   // 4: game.PlayerInput
}
var file_proto_game_proto_depIdxs = []int32{
	1, // 0: game.WorldSnapshot.snakes:type_name -> game.Snake
	2, // 1: game.WorldSnapshot.coins:type_name -> game.Coin
	3, // 2: game.Snake.head:type_name -> game.Point
	3, // 3: game.Snake.body:type_name -> game.Point
	3, // 4: game.Coin.pos:type_name -> game.Point
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_proto_game_proto_init() }
func file_proto_game_proto_init() {
	if File_proto_game_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_game_proto_rawDesc), len(file_proto_game_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_game_proto_goTypes,
		DependencyIndexes: file_proto_game_proto_depIdxs,
		MessageInfos:      file_proto_game_proto_msgTypes,
	}.Build()
	File_proto_game_proto = out.File
	file_proto_game_proto_goTypes = nil
	file_proto_game_proto_depIdxs = nil
}
